version: '3.5'

services:
  schedule-app-postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: schedule-app
    ports:
      - '5432:5432'
    volumes:
      - schedule-app-db:/var/lib/postgresql/schedule-app

  schedule-app-redis:
    image: redis
    ports:
      - '6379:6379'
    command: >
      --user user on allcommands allkeys >pass
    restart: unless-stopped

volumes:
  schedule-app-db: